-- Ver todos los equipos y su tipo visual PUNTOS
SELECT ID, EQUIPO, LOCALIZACION, COALESCE(PUNTOS, 0) AS PUNTOS, TAGNAME
FROM PTBG_DAT.MOT_EQUIPO
ORDER BY LOCALIZACION;

-- Ver equipos con PUNTOS = 0
SELECT ID, EQUIPO, LOCALIZACION, COALESCE(PUNTOS, 0) AS PUNTOS, TAGNAME
FROM PTBG_DAT.MOT_EQUIPO
WHERE COALESCE(PUNTOS, 0) = 0
ORDER BY LOCALIZACION;

-- Consulta principal que debe devolver también equipos con PUNTOS=0
SELECT
    e.ID,
    e.CODE_SYS,
    e.EQUIPO,
    e.LOCALIZACION,
    e.NAME_SYS_1,
    e.NAME_SYS_2,
    e.CODE_QR,
    COALESCE(e.PUNTOS, 0) AS PUNTOS,
    e.TAGNAME,
    d.MARCA,
    d.MODELO,
    d.SERIAL,
    d.VOLTAJE,
    d.CORRIENTE,
    d.RPM,
    d.SF,
    d.HP,
    d.FRAME
FROM PTBG_DAT.MOT_EQUIPO e
LEFT JOIN PTBG_DAT.MOT_DATA d ON d.UBICACION = e.LOCALIZACION
ORDER BY e.LOCALIZACION;
