-- SCV-PTBG V28 - Validación estructura oficial PTBG_DAT
USE PTBG_DAT;

-- 1) Estado de equipos + datos técnicos
SELECT
    e.ID,
    e.CODE_SYS,
    e.EQUIPO,
    e.LOCALIZACION,
    e.NAME_SYS_1,
    e.NAME_SYS_2,
    e.CODE_QR,
    e.PUNTOS,
    e.TAGNAME,
    s.ID AS SYS_ID,
    s.SISTEMA,
    s.CODE AS SYS_CODE,
    s.NAME_SYS,
    d.ID AS DATA_ID,
    d.FECHA,
    d.HORA,
    d.MARCA,
    d.MODELO,
    d.VOLTAJE,
    d.CORRIENTE,
    d.SERIAL,
    d.RPM,
    d.SF,
    d.HP,
    d.FRAME,
    d.BRGS_DRIVE,
    d.BRGS_OPP,
    d.CICLO,
    d.UBICACION,
    d.CODE_CONJUNTO,
    d.ARRANQUE,
    d.PH,
    d.TENSION,
    d.LUBRICACION
FROM MOT_EQUIP e
LEFT JOIN MOT_SYSTEM s ON s.CODE = e.CODE_SYS
LEFT JOIN MOT_DATA d ON d.UBICACION = e.LOCALIZACION
ORDER BY e.LOCALIZACION;

-- 2) Equipos sin tipo visual válido
SELECT ID, EQUIPO, LOCALIZACION, PUNTOS, TAGNAME
FROM MOT_EQUIP
WHERE PUNTOS IS NULL OR PUNTOS = 0 OR PUNTOS NOT BETWEEN 1 AND 9
ORDER BY LOCALIZACION;

-- 3) Equipos sin datos técnicos en MOT_DATA
SELECT e.ID, e.EQUIPO, e.LOCALIZACION, e.PUNTOS, e.TAGNAME
FROM MOT_EQUIP e
LEFT JOIN MOT_DATA d ON d.UBICACION = e.LOCALIZACION
WHERE d.UBICACION IS NULL
ORDER BY e.LOCALIZACION;

-- 4) Prueba QR numérico por localización
SELECT e.ID, e.EQUIPO, e.LOCALIZACION, e.CODE_QR, e.PUNTOS, e.TAGNAME,
       d.MARCA, d.MODELO, d.SERIAL, d.VOLTAJE, d.CORRIENTE, d.RPM, d.HP
FROM MOT_EQUIP e
LEFT JOIN MOT_DATA d ON d.UBICACION = e.LOCALIZACION
WHERE e.CODE_QR = '1'
   OR e.TAGNAME = '1'
   OR CAST(e.LOCALIZACION AS CHAR) = '1'
   OR CAST(e.ID AS CHAR) = '1'
LIMIT 1;
