-- V31: Validar última lectura por equipo con nombre y tagname

SELECT
  e.LOCALIZACION,
  e.EQUIPO,
  e.TAGNAME,
  e.PUNTOS,
  m.ID AS ID_MEDICION,
  m.FECHA,
  m.HORA,
  m.H1, m.V1, m.A1,
  m.H2, m.V2, m.A2,
  m.RMS,
  m.OBSERVACIONES
FROM MOT_EQUIPO e
INNER JOIN (
  SELECT LOCALIZACION, MAX(ID) AS MAX_ID
  FROM MOT_VIBR_MUES
  GROUP BY LOCALIZACION
) last_m ON last_m.LOCALIZACION = e.LOCALIZACION
INNER JOIN MOT_VIBR_MUES m ON m.ID = last_m.MAX_ID
ORDER BY e.LOCALIZACION;

-- Ver equipos sin medición histórica todavía
SELECT
  e.LOCALIZACION,
  e.EQUIPO,
  e.TAGNAME,
  e.PUNTOS
FROM MOT_EQUIPO e
LEFT JOIN (
  SELECT DISTINCT LOCALIZACION
  FROM MOT_VIBR_MUES
) m ON m.LOCALIZACION = e.LOCALIZACION
WHERE m.LOCALIZACION IS NULL
ORDER BY e.LOCALIZACION;
