-- V32 - Validar que se obtiene UNA sola última lectura por LOCALIZACION

-- 1) Resumen general
SELECT
    COUNT(*) AS TOTAL_REGISTROS,
    COUNT(DISTINCT LOCALIZACION) AS TOTAL_LOCALIZACIONES,
    MIN(ID) AS MIN_ID,
    MAX(ID) AS MAX_ID
FROM MOT_VIBR_MUES
WHERE LOCALIZACION IS NOT NULL;

-- 2) Cuántas mediciones tiene cada LOCALIZACION y cuál es su último ID
SELECT
    LOCALIZACION,
    COUNT(*) AS CANTIDAD,
    MIN(ID) AS PRIMER_ID,
    MAX(ID) AS ULTIMO_ID
FROM MOT_VIBR_MUES
WHERE LOCALIZACION IS NOT NULL
GROUP BY LOCALIZACION
ORDER BY LOCALIZACION;

-- 3) Consulta final que usa el backend: última lectura por LOCALIZACION con nombre y tag
SELECT
    last_m.LOCALIZACION,
    last_m.MAX_ID AS ID_ULTIMA,
    e.EQUIPO,
    e.TAGNAME,
    m.FECHA,
    m.HORA,
    m.RMS
FROM (
    SELECT LOCALIZACION, MAX(ID) AS MAX_ID
    FROM MOT_VIBR_MUES
    WHERE LOCALIZACION IS NOT NULL
    GROUP BY LOCALIZACION
) last_m
INNER JOIN MOT_VIBR_MUES m
    ON m.ID = last_m.MAX_ID
   AND m.LOCALIZACION = last_m.LOCALIZACION
LEFT JOIN MOT_EQUIPO e
    ON e.LOCALIZACION = last_m.LOCALIZACION
ORDER BY last_m.LOCALIZACION;

-- 4) Localizaciones de MOT_EQUIPO que todavía no tienen medición histórica
SELECT
    e.LOCALIZACION,
    e.EQUIPO,
    e.TAGNAME
FROM MOT_EQUIPO e
LEFT JOIN MOT_VIBR_MUES m ON m.LOCALIZACION = e.LOCALIZACION
WHERE m.ID IS NULL
ORDER BY e.LOCALIZACION;
