-- V30 - Consultas de validación PTBG_DAT
USE PTBG_DAT;

-- 1) Equipos oficiales
SELECT ID, CODE_SYS, EQUIPO, LOCALIZACION, NAME_SYS_1, NAME_SYS_2, CODE_QR, PUNTOS, TAGNAME
FROM MOT_EQUIPO
ORDER BY LOCALIZACION;

-- 2) Cruce de equipos con datos técnicos
SELECT
  e.ID,
  e.EQUIPO,
  e.LOCALIZACION,
  e.PUNTOS,
  e.TAGNAME,
  d.MARCA,
  d.MODELO,
  d.SERIAL,
  d.VOLTAJE,
  d.CORRIENTE,
  d.RPM,
  d.HP
FROM MOT_EQUIPO e
LEFT JOIN MOT_DATA d ON d.UBICACION = e.LOCALIZACION
ORDER BY e.LOCALIZACION;

-- 3) Última medición por cada equipo/localización
SELECT
  m.ID,
  m.FECHA,
  m.HORA,
  m.LOCALIZACION,
  e.EQUIPO,
  e.TAGNAME,
  m.RMS,
  m.OBSERVACIONES
FROM MOT_VIBR_MUES m
INNER JOIN (
  SELECT LOCALIZACION, MAX(ID) AS MAX_ID
  FROM MOT_VIBR_MUES
  GROUP BY LOCALIZACION
) last_m ON last_m.LOCALIZACION = m.LOCALIZACION AND last_m.MAX_ID = m.ID
LEFT JOIN MOT_EQUIPO e ON e.LOCALIZACION = m.LOCALIZACION
ORDER BY m.LOCALIZACION;

-- 4) Localizaciones sin medición previa
SELECT e.LOCALIZACION, e.EQUIPO, e.TAGNAME
FROM MOT_EQUIPO e
LEFT JOIN (
  SELECT DISTINCT LOCALIZACION FROM MOT_VIBR_MUES
) m ON m.LOCALIZACION = e.LOCALIZACION
WHERE m.LOCALIZACION IS NULL
ORDER BY e.LOCALIZACION;
